### ISSUE TITLE
Custom keybindings ignored

### ISSUE THREAD

**Issue by tyten** [atom/grammar-selector#19]
Set a custom keybinding to replace, say, ctrl-shift-l and grammar selector comes up no matter what.

**Comment by lee-dohm** [comment]
I cannot reproduce this using Atom v0.197.0-a79a8fa on Mac OS X 10.10.3. Keybindings follow [specificity rules](https://atom.io/docs/latest/behind-atom-keymaps-in-depth#specificity-and-cascade-order) like CSS, so it may be that you're not writing a selector that is at least as specific as the one that declared the one for the grammar selector.

Here's what I did to override the <kbd>Ctrl+Shift+L</kbd> keybinding:

1. Open Atom
1. Open the Settings View (you can use either <kbd>Cmd+,</kbd> on OS X or <kbd>Ctrl+,</kbd> on Linux/Windows)
1. Click the keybindings tab
1. Search for "grammar" in the search field
1. Click the clipboard icon to the left of the command `grammar-selector:show` to copy the keybinding declaration to the clipboard
1. Open the `keymap.cson` using the menu item
1. Paste in the declaration at the bottom
1. Change the command to something like `application:open-file`
1. Save the changes

Then you can test the changes by pressing <kbd>Ctrl+Shift+L</kbd>.

Let me know if you have any other questions!

**Comment by LoneBoco** [comment]
It looks like this bug is triggered based on the order of your keybindings.  Take this example.  It will prevent the grammar-selector from working:
```
'.platform-win32 atom-text-editor':
  'ctrl-shift-B': 'grammar-selector:show'

'.platform-win32 atom-text-editor':
  'ctrl-shift-L': 'editor:split-selections-into-lines'
```

If you reverse the order of those two keybinds, it will work properly.

**Comment by 50Wliu** [comment]
@LoneBoco the keybindings file is in CSON format (which requires that different keys be unique) so your example should look like this instead:
```cson
'.platform-win32 atom-text-editor':
  'ctrl-shift-B': 'grammar-selector:show'
  'ctrl-shift-L': 'editor:split-selections-into-lines'
```

**Comment by izuzak** [comment]
@tyten -- let us know if you can still reproduce this in Atom 1.0.3, and please provide the exact steps which reproduce the issue for you. (Check out the notes in the comments above :point_up: for some advice.)
