### ISSUE TITLE
Enhancement request: Grammar directive

### ISSUE THREAD

**Issue by bortels** [atom/grammar-selector#23]
If this feature already exists, consider this a documentation gap. :-)

For some reason, a the grammar auto-guesser comes up "plain text" for me fairly often. I can change it, but when I reload the file later, I have to set it again. 

It would be nice if you could add a directive to your file to trigger a specific language. Something like

    # atom-grammar: ruby

And them maybe simply check any line in the doc (or the first part for a big doc) for ending in " atom-grammar: THIS" and set the grammar to THIS if it exists. (I assume most languages have a single-line comment)

Part of me thinks maybe that should be an entirely different package, something to keep metadata (Code folding, I'm looking at you as well) associated with a document.

**Comment by tiagocpontesp** [comment]
I'd rather have a priority list of some sort with filename regexes (would this also fix linter priorities?).

**Comment by lee-dohm** [comment]
There are a couple packages for this already:

* https://atom.io/packages/file-mode
* https://atom.io/packages/grammar-mode

**Comment by tiagocpontesp** [comment]
This can probably be closed. Just want to leave a reference for a similar package, that mostly resolves the issue through filename parsing:
https://atom.io/packages/file-types
