### ISSUE TITLE
Jade now called pug

### ISSUE THREAD

**Issue by skbolton** [atom/grammar-selector#31]
Since Jade is going to be changing its name to pug because of legal issues I was wondering if there is a way that .pug files would be recognized as jade files. Or to be more forward thinking if pug was an option for the grammar selection

**Comment by lee-dohm** [comment]
You could submit an Issue on the [language-jade package](https://atom.io/packages/language-jade) to add support for the additional file extension. In addition, you could add support yourself using the `customFileTypes` setting in Atom. See the [Atom FAQ](https://discuss.atom.io/c/faq) for details:

https://discuss.atom.io/t/how-do-i-make-atom-recognize-a-file-with-extension-x-as-language-y/26539

Also, [we're trying to control the amount of Issues that we have to triage](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
